version: "3"
services:
  php:
    build: ./docker-conf/php/
    working_dir: /var/www/project
    volumes:
        - ./:/var/www/project
    tty: true
    expose:
      - 9000
    links:
      - postgres
      - postgres_test
  nginx:
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/project
      - ./docker-conf/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  postgres:
    image: postgres:9.6
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_ROOT_PASSWORD=${DB_PASSWORD}"
    ports:
      - 54320:${DB_PORT}
  postgres_test:
    image: postgres:9.6
    volumes:
      - postgrestestdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${DB_DATABASE}_tests"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_ROOT_PASSWORD=${DB_PASSWORD}"
    ports:
      - 54321:${DB_PORT}
volumes:
  postgresdata:
  postgrestestdata: